# Configuration settings for map processing pipeline

# Path configurations
paths:
  mxd_input: "data/input/mxd"
  aprx_input: "data/input/aprx"
  pdf_output: "data/output/pdf"
  logs: "data/output/logs"

# Processing options
options:
  default_year: 2024
  pdf_resolution: 300
  overwrite_existing: false

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
